### PR TITLE
Include support for load domain

### PR DESCRIPTION
**Pull request by inode64**
I have adjusted your configuration class to load an existing domain and thus then create the getDisk, getEthernet, get ... functions.

If you see it well and continue in that line.
Help me if you see something wrong.
I attach an example

Greetings

<pre>
require_once __DIR__ . '/vendor/autoload.php';

use YunInternet\Libvirt\Connection;
use YunInternet\Libvirt\Configuration\Domain;

$connection = new Connection("localhost://test/system");
$dom = $connection->domainLookupByName('example');
$domain = $dom->getDomain();

$disk = $domain->device()->getDisk('vda');
$eth0 = $domain->device()->getInterface('xx:xx:xx:xx:xx:xx');
</pre>

### CODE REVIEW

**Comment by yzslab** [comment]
I think make such a change to the constructor isn't a good idea. It will break my code rely on it.
Try to make changes backward compatible, like:
```
public function __construct($name, $memory = null, $maxAllocatedVCPU = null, $type = "kvm")
{
    if (is_null($memory)) {
        parent::__construct(new \SimpleXMLElement($xml));
    } else {
        parent::__construct(new \SimpleXMLElement("<domain/>"));
        ...
    }
}
```
or other ways if you have better idea.
Renaming method getDomain() to a name which can explain itself will be better, I just feel "getDomain" is a little bit ambiguous.

There isn't any problem with the functions you want to implement, feel free to proceed your work.
Thanks.

**Comment by yzslab** [comment]
I made some changes to this package just now.
YunInternet\Libvirt\Domain::createConfigurationWithXML() can be used to create an instance of class located in YunInternet\Libvirt\Configuration with exists XML.
I also migrated several functions from my system to this package, such as YunInternet\Libvirt\Domain::changeMedia(), YunInternet\Libvirt\Domain::getDiskByTargetDev(), YunInternet\Libvirt\Domain::attachDisk(), YunInternet\Libvirt\Domain::detachDiskByTargetDev() and etc. I don't know whether they can solve a part of your problems.

**Comment by inode64** [comment]
ooohhh
I am going to study the changes, you have made many !!
thanks

**Comment by yzslab** [comment]
> ooohhh
> I am going to study the changes, you have made many !!
> thanks

Hi, your $domain = $dom->getDomain() has been implemented as YunInternet\Libvirt\Domain::getConfigurationBuilder(). 
I don't know whether you noticed it. README also contains new examples.

**Comment by inode64** [comment]
I had already done something, but your code is much better.
Thanks.

**Pull request closed without merging**
