### PR TITLE
Small fix in composer

### PR DESCRIPTION
**Pull request by inode64**
Remove duplicate entries for ext-json
Update to PHP 7.2, include void, object  and Nullable types 

If possible to update

### CODE REVIEW

**Comment by yzslab** [comment]
I haven't test whether my system compatible with 7.2, so try not to change the PHP version, thanks.

**Comment by inode64** [comment]
I with 7.1?

**Comment by yzslab** [comment]
> I with 7.1?

Deciding it later.

**Comment by inode64** [comment]
Restore to 7.0


When you can update your servers to a higher version, make a commit, I use versions 7.0 to 7.4 on my servers and I will not have problems.

Thanks

**Pull request merged**
