### PR TITLE
Various features

### PR DESCRIPTION
**Pull request by inode64**
Update conditionals and loops to support PSR-12
New dictionary
Include json dependency in composer

### CODE REVIEW

**Comment by inode64** [comment]
Sorry for closing only one patch, I made a mistake creating the branch.
Is there a problem with them?

**Review by yzslab — COMMENTED** [review]
> Sorry for closing only one patch, I made a mistake creating the branch.
> Is there a problem with them?

Hi, everything is good, I just want to know the function of the file "libvirt-php-client.dic". I submitted a review comment several days ago but didn't receive your reply.

**Comment by yzslab** [comment]
Hi, the commit 8704b5f and 04738cb were merged!
Thanks for you contributions!

**Comment by inode64** [comment]
I'm sorry,
The file libvirt-php-client.dic is a dictionary for spelling , I'm use in phpstorm for correct writing. (doc, params, functions. etc..)

**Comment by yzslab** [comment]
> I'm sorry,
> The file libvirt-php-client.dic is a dictionary for spelling , I'm use in phpstorm for correct writing. (doc, params, functions. etc..)

Hi, I think add my name "Zhensheng" to that file isn't necessary, would you mind removing the first line of the file libvirt-php-client.dic?

**Comment by inode64** [comment]
in others projects are include the developer 's name , example https://github.com/networkupstools/nut/blob/master/docs/nut.dict

**Comment by inode64** [comment]
I remove Zhensheng and I include new words

**Comment by yzslab** [comment]
Hi, thanks for your contribution! Your 0ddbd1f were merged: https://github.com/yzslab/php-libvirt-client/commit/6b23c7fe1c2ef4b30497b8b5610fb4422ad9a621
I think this pull request can be closed now.

**Pull request closed without merging**
